# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ BricksSiteBundle, BricksUserBundle ]
    java:           %java_path%
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        lessphp: ~
    assets:
        lesses:
            inputs:
                - %kernel.root_dir%/../web/assets/bootstrap/less/bootstrap.less
                - @BricksSiteBundle/Resources/less/*.less
                - @BricksUserBundle/Resources/less/*.less
            filters: lessphp
        stylesheets:
            inputs:
                - @lesses
                - %kernel.root_dir%/../web/assets/FontAwesome/css/font-awesome.css
            filters:
                - cssrewrite
                - ?yui_css
        javascripts:
            inputs:
                - %kernel.root_dir%/../web/assets/jquery/jquery-1.8.2.js
                - %kernel.root_dir%/../web/assets/bootstrap/js/bootstrap-transition.js
                - %kernel.root_dir%/../web/assets/bootstrap/js/bootstrap-dropdown.js
                - %kernel.root_dir%/../web/assets/bootstrap/js/bootstrap-tab.js
                - %kernel.root_dir%/../web/assets/bootstrap/js/bootstrap-alert.js
                - %kernel.root_dir%/../web/assets/bootstrap/js/bootstrap-modal.js
                - %kernel.root_dir%/../web/assets/bootstrap/js/bootstrap-tooltip.js
                - %kernel.root_dir%/../web/assets/bootstrap-tags/lib/bootstrap-tags.js
                - bundles/fosjsrouting/js/router.js
                - @BricksSiteBundle/Resources/js/*.js
                - @BricksSiteBundle/Resources/js/*/*.js
            filters:
                - cssrewrite
                - ?yui_css
