hwi_oauth:

    firewall_name: main

    connect:
        account_connector: bricks.user_provider

    # optional FOSUserBundle integration
    fosub:
        # try 30 times to check if a username is available (foo, foo1, foo2 etc)
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            github: githubId
            twitter: twitterId

    resource_owners:
        github:
            type:           github
            client_id:      %oauth_github_client_id%
            client_secret:  %oauth_github_client_secret%
            scope:          "user:email"
        twitter:
            type:           twitter
            client_id:      %oauth_twitter_client_id%
            client_secret:  %oauth_twitter_client_secret%
            #scope:          "user:email"