services:

    # Brick Twig extenxion
    bricks.twig.brick_extension:
        class: Bricks\SiteBundle\Extension\BrickExtension
        arguments: [@router]
        tags:
           - { name: twig.extension }

    # Enables TWIG Text Extension
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    # Sitemap Listener
    bricks.sitemap.listener:
        class: Bricks\SiteBundle\Listener\SitemapListener
        arguments: [@router, @doctrine.orm.entity_manager, %interface_translation_locales%]
        tags:
            - { name: presta.sitemap.listener }

    # custom file namer
    bricks.namer_uniqid:
        class: Bricks\SiteBundle\Namer\BricksNamer